export const LOAD_ROLES_LIST = 'LOAD_ROLES_LIST';
export const LOAD_CATEGORIAS_LIST = 'LOAD_CATEGORIAS_LIST';
export const LOAD_PRODUCTOS_LIST = 'LOAD_PRODUCTOS_LIST';
export const SAVE_PRODUCTOS = 'SAVE_PRODUCTOS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
